apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 8080;
            location / {
                return 200 'Hello, world!';
                add_header Content-Type text/plain;
            }
        }
    }
